export const ORIGEN_ATRIBUTO=[
    "G",
    "D",
    "C",
]

export const ESTADO = [
    "A",
    "I",
]
export const DESCRIPCION_ATRIBUTO =[
    "GRUPO DE INGRESOS",
    "CUOTA PRESTAMO(S) INTERNO(S)",
    "CUOTA PRESTAMO(S) EXTERNO(S)",
    "TOTAL GASTOS",
    "INGRESOS NETOS",
    "SUELDO SOLICITANTE RD$",
    "SUELDO SOLICITANTE US$",
    "OTROS INGRESOS",
    "SUELDO CONYUGUE",
    "TOTAL INGRESOS",
    "GASTOS",
    "ALQUILERES",
    "SERVICIOS (AGUA, TEL., ENERGIA, OTROS)",
    "ALIMENTACION"
]